[features]
seeds = false
[programs.devnet]
programs = "6gJjDRBJZHEgxB7Wzk4dHQJwwy9XoMdKiAnEBxxgG71L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/deca28/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

